// Validation pack (DEC-081): user requirements, risk assessment, traceability
// matrix and the executed operational qualification (the automated test run),
// generated by CI for every commit from docs/validation/requirements.json and
// the vitest JSON reports. Pure functions plus a small command-line entry; it
// imports nothing local so Node can run it directly (--experimental-strip-types).
//
// Run: node --experimental-strip-types src/lib/validation-pack.ts \
//   --requirements docs/validation/requirements.json --report unit.json --report db.json \
//   --out validation-pack --commit <sha>

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

export type Requirement = {
  id: string;
  area: string;
  requirement: string;
  source: string;
  hazard: string;
  severity: number;
  likelihood: number;
  control: string;
  tests: string[];
};

export type TestResult = { id: string | null; title: string; file: string; suite: string; status: string; durationMs: number };

type VitestReport = {
  testResults?: Array<{
    name: string;
    assertionResults?: Array<{ title: string; fullName?: string; status: string; duration?: number | null; ancestorTitles?: string[] }>;
  }>;
};

const TEST_ID = /^([A-Z][A-Z0-9]*(?:-[A-Z0-9]+)*-T\d{3})\b/;

export function riskClass(severity: number, likelihood: number): 'High' | 'Medium' | 'Low' {
  const score = severity * likelihood;
  return score >= 6 ? 'High' : score >= 3 ? 'Medium' : 'Low';
}

export function readResults(report: VitestReport, suite: string, root = ''): TestResult[] {
  return (report.testResults ?? []).flatMap((file) => (file.assertionResults ?? []).map((test) => ({
    id: TEST_ID.exec(test.title)?.[1] ?? null,
    title: test.title,
    file: root ? relative(root, file.name) : file.name,
    suite,
    status: test.status,
    durationMs: Math.round(test.duration ?? 0),
  })));
}

export type Trace = {
  requirement: Requirement;
  risk: 'High' | 'Medium' | 'Low';
  tests: Array<{ id: string; results: TestResult[]; verdict: 'passed' | 'failed' | 'missing' }>;
  verdict: 'verified' | 'not verified';
  problems: string[];
};

export function trace(requirements: Requirement[], results: TestResult[]): Trace[] {
  return requirements.map((requirement) => {
    const tests = requirement.tests.map((id) => {
      const found = results.filter((result) => result.id === id);
      const verdict: 'passed' | 'failed' | 'missing' = found.length === 0 ? 'missing'
        : found.every((result) => result.status === 'passed') ? 'passed' : 'failed';
      return { id, results: found, verdict };
    });
    const problems = [
      ...(tests.length === 0 ? ['no test is linked'] : []),
      ...tests.filter((test) => test.verdict === 'missing').map((test) => `${test.id} was not found in the test run`),
      ...tests.filter((test) => test.verdict === 'failed').map((test) => `${test.id} did not pass`),
    ];
    return {
      requirement,
      risk: riskClass(requirement.severity, requirement.likelihood),
      tests,
      verdict: problems.length === 0 ? 'verified' : 'not verified',
      problems,
    };
  });
}

export type PackContext = { commit: string; generatedAt: Date; runner: string };

const cell = (text: string) => text.replace(/\|/g, '\\|').replace(/\n/g, ' ');

function header(title: string, context: PackContext) {
  return [
    `# ${title}`,
    '',
    `Commit \`${context.commit}\` · generated ${context.generatedAt.toISOString()} · ${context.runner}`,
    '',
    '> Generated automatically from the repository and the test run of this commit. It is evidence for review by a qualified person; it is not an approval.',
    '',
  ];
}

export function renderUrs(requirements: Requirement[], context: PackContext): string {
  const lines = header('User requirements specification', context);
  for (const area of [...new Set(requirements.map((requirement) => requirement.area))]) {
    lines.push(`## ${area}`, '', '| ID | Requirement | Source |', '| --- | --- | --- |');
    for (const requirement of requirements.filter((item) => item.area === area)) {
      lines.push(`| ${requirement.id} | ${cell(requirement.requirement)} | ${cell(requirement.source)} |`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

export function renderRisk(traces: Trace[], context: PackContext): string {
  const lines = header('Risk assessment', context);
  lines.push(
    'Severity and likelihood from 1 (low) to 3 (high); risk class from their product: 6 or more High, 3 to 5 Medium, below 3 Low.',
    '',
    '| ID | Hazard | Severity | Likelihood | Risk | Control | Verified by |',
    '| --- | --- | --- | --- | --- | --- | --- |',
  );
  for (const item of traces) {
    const { requirement } = item;
    lines.push(`| ${requirement.id} | ${cell(requirement.hazard)} | ${requirement.severity} | ${requirement.likelihood} | ${item.risk} | ${cell(requirement.control)} | ${requirement.tests.length} tests |`);
  }
  return lines.join('\n') + '\n';
}

export function renderTraceability(traces: Trace[], context: PackContext): string {
  const lines = header('Traceability matrix', context);
  lines.push('| Requirement | Risk | Tests | Result |', '| --- | --- | --- | --- |');
  for (const item of traces) {
    const tests = item.tests.map((test) => `${test.id} (${test.verdict})`).join(', ') || '—';
    lines.push(`| ${item.requirement.id} | ${item.risk} | ${tests} | ${item.verdict === 'verified' ? 'Verified' : `**Not verified:** ${cell(item.problems.join('; '))}`} |`);
  }
  return lines.join('\n') + '\n';
}

export function renderOq(results: TestResult[], context: PackContext): string {
  const lines = header('Operational qualification: executed test record', context);
  const count = (status: string) => results.filter((result) => result.status === status).length;
  lines.push(
    `${results.length} tests executed: ${count('passed')} passed, ${count('failed')} failed, ${results.length - count('passed') - count('failed')} skipped.`,
    '',
  );
  for (const suite of [...new Set(results.map((result) => result.suite))]) {
    lines.push(`## ${suite}`, '', '| Test ID | Test | File | Result | ms |', '| --- | --- | --- | --- | --- |');
    for (const result of results.filter((item) => item.suite === suite)) {
      lines.push(`| ${result.id ?? '—'} | ${cell(result.title)} | ${cell(result.file)} | ${result.status} | ${result.durationMs} |`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

export function renderSummary(traces: Trace[], results: TestResult[], context: PackContext): string {
  const failing = results.filter((result) => result.status === 'failed');
  const unverified = traces.filter((item) => item.verdict !== 'verified');
  const passed = unverified.length === 0 && failing.length === 0;
  const lines = header('Validation pack', context);
  lines.push(
    `**Result: ${passed ? 'all requirements verified, all tests passed' : 'NOT complete'}**`,
    '',
    `- ${traces.length} requirements (${traces.filter((item) => item.risk === 'High').length} high risk), ${traces.length - unverified.length} verified`,
    `- ${results.length} tests executed, ${failing.length} failed`,
    '',
    'Contents: `URS.md` (requirements), `risk-assessment.md`, `traceability-matrix.md`, `OQ-execution.md` (executed test record).',
    '',
  );
  if (unverified.length > 0) {
    lines.push('## Requirements not verified', '');
    for (const item of unverified) lines.push(`- ${item.requirement.id}: ${item.problems.join('; ')}`);
    lines.push('');
  }
  if (failing.length > 0) {
    lines.push('## Failed tests', '');
    for (const result of failing) lines.push(`- ${result.id ?? result.title} (${result.file})`);
    lines.push('');
  }
  return lines.join('\n');
}

export function buildPack(requirements: Requirement[], results: TestResult[], context: PackContext) {
  const traces = trace(requirements, results);
  const complete = traces.every((item) => item.verdict === 'verified') && results.every((result) => result.status !== 'failed');
  return {
    complete,
    files: {
      'README.md': renderSummary(traces, results, context),
      'URS.md': renderUrs(requirements, context),
      'risk-assessment.md': renderRisk(traces, context),
      'traceability-matrix.md': renderTraceability(traces, context),
      'OQ-execution.md': renderOq(results, context),
    } as Record<string, string>,
  };
}

function main(argv: string[]) {
  const value = (flag: string) => argv[argv.indexOf(flag) + 1];
  const reports = argv.flatMap((arg, index) => (arg === '--report' ? [argv[index + 1]] : []));
  const requirements = (JSON.parse(readFileSync(value('--requirements'), 'utf8')) as { requirements: Requirement[] }).requirements;
  const results = reports.flatMap((path) => {
    const suite = path.includes('db') ? 'Database and two-tenant isolation tests' : 'Unit tests';
    return readResults(JSON.parse(readFileSync(path, 'utf8')) as VitestReport, suite, process.cwd());
  });
  const context = { commit: value('--commit') ?? 'local', generatedAt: new Date(), runner: `Node ${process.version}` };
  const pack = buildPack(requirements, results, context);
  const out = value('--out');
  mkdirSync(out, { recursive: true });
  for (const [name, content] of Object.entries(pack.files)) writeFileSync(join(out, name), content);
  process.stdout.write(pack.files['README.md']);
  if (!pack.complete) process.exitCode = 1;
}

if (process.argv[1]?.endsWith('validation-pack.ts')) main(process.argv.slice(2));
